version: "3.9"

services:
  # --------------------------
  # Postgres (Airflow metadata)
  # --------------------------
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --------------------------
  # MySQL (Data Warehouse)
  # --------------------------
  mysql:
    image: mysql:8.0
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=finance_dw
      - MYSQL_USER=etl_user
      - MYSQL_PASSWORD=etl_pass
    ports:
      - "3307:3306"  # external:internal
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # --------------------------
  # Airflow Initialization
  # --------------------------
  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=${_PIP_ADDITIONAL_REQUIREMENTS}
    entrypoint: /bin/bash
    command: >
      -c "airflow db init &&
          airflow users create --username airflow --password airflow
          --firstname Air --lastname Flow --role Admin --email admin@example.com"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../config:/opt/airflow/config
      - ../data:/opt/airflow/data
      - ../logs:/opt/airflow/logs
      - ../.env:/opt/airflow/.env

  # --------------------------
  # Airflow Webserver
  # --------------------------
  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
      - _PIP_ADDITIONAL_REQUIREMENTS=${_PIP_ADDITIONAL_REQUIREMENTS}
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../config:/opt/airflow/config
      - ../data:/opt/airflow/data
      - ../logs:/opt/airflow/logs
      - ../.env:/opt/airflow/.env

  # --------------------------
  # Airflow Scheduler
  # --------------------------
  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
      - _PIP_ADDITIONAL_REQUIREMENTS=${_PIP_ADDITIONAL_REQUIREMENTS}
      - DATA_DIR=${DATA_DIR}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    command: scheduler
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../config:/opt/airflow/config
      - ../data:/opt/airflow/data
      - ../logs:/opt/airflow/logs
      - ../.env:/opt/airflow/.env

volumes:
  airflow-db:
  mysql-data: